Ticket.UI.Web/Models/RequestResult.cs
namespace Ticket.UI.Web.Models
{
    public enum RequestResultType
    {
        Success,
        Failed,
        Warning,
        Info
    }

    public class RequestResult
    {
        public RequestResultType ResultType { get; set; }
        public string Message { get; set; }
    }
}

Ticket.UI.Web/Controllers/CompanyController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="CompanyController.cs" company="">
//   
// </copyright>
// <summary>
//   The company controller.
// </summary>
// --------------------------------------------------------------------------------------------------------------------


namespace Ticket.UI.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Text;
    using System.Web.Mvc;
    using Ticket.Domain;
    using Ticket.Interfaces.Business;
    using Ticket.UI.Web.Models;
    using Ticket.UI.Web.ViewModels;

    /// <summary>
    /// The company controller.
    /// </summary>
    public class CompanyController : TicketControllerBase
    {

        /// <summary>
        /// The cs.
        /// </summary>
        private readonly ICompanyService cs;

        /// <summary>
        /// Initializes a new instance of the <see cref="CompanyController"/> class.
        /// </summary>
        /// <param name="cs">
        /// The cs.
        /// </param>
        public CompanyController(ICompanyService cs)
        {
            this.cs = cs;
        }


        /// <summary>
        /// The register.
        /// </summary>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        public ActionResult Register()
        {
            var company = new Company();

            return this.View(company);
        }

        /// <summary>
        /// The register.
        /// </summary>
        /// <param name="company">
        /// The company.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpPost]
        public ActionResult Register(Company company)
        {
            //if (!ModelState.IsValid)
            //{
            //    return View(company);
            //}

            this.cs.CreateCompany(company);

            return this.View(company);
        }

        [HttpGet]
        public ActionResult Setup(int id)
        {
            // fetch the company 
            var company = this.cs.GetCompanyById(id);
            var busses = this.cs.GetBusses(id);
            var routes = this.cs.GetListOfRoutes(id);

            if (company == null)
            {
                this.ModelState.AddModelError("notfound", "Company not found");
            }

            var setupVm = new CompanySetupViewModel();
            setupVm.Company = company;
            setupVm.Busses = busses;
            setupVm.Routes = routes;

            return this.View(setupVm);
        }

        [HttpPost]
        public ActionResult UpdateCompanyInfo(Company company)
        {
            var badFields = new StringBuilder();
            //if (!ModelState.IsValid)
            //{
            //    foreach (var k in this.ModelState.Keys.Where(k => !this.ModelState.IsValidField(k)))
            //    {
            //        badFields.Append(k);
            //        badFields.Append(" ");
            //    }

            //    return this.SendRequestResult(string.Format("Please correct the errors in {0} and submit again", badFields.ToString()), RequestResultType.Warning);
            //}

            try
            {
                //this.cs.EditCompany(company);
                return this.SendJsonRequestResult("Data saved", true, null);
            }
            catch (Exception ex)
            {
                return this.SendJsonRequestResult(ex.Message, false, null);
            }

        }

        [HttpPost]
        public ActionResult AddBus(int id, Bus bus)
        {
            var company = this.cs.GetCompanyById(id);
            this.cs.AddBus(company, bus);

            return this.SendJsonRequestResult("Bus created", true, new {id = bus.Id});
        }

        [HttpDelete]
        public ActionResult RemoveBus(int id)
        {
            throw new NotImplementedException();
        }

        [HttpPost]
        public ActionResult UpdateBusses(int id, Bus bus)
        {

            return this.SendRequestResult("Data saved", RequestResultType.Success);
        }

        //public ActionResult CreateBus(int id)
        //{
        //    return this.PartialView("_BussesTab")
        //}

        [HttpPost]
        public ActionResult Payment(int id, Company company)
        {

            return this.SendRequestResult("Data saved", RequestResultType.Success);
        }

        [HttpPost]
        public ActionResult EditRoute(int id, Location start, Location destination)
        {
            var routes = this.cs.GetListOfRoutes(id).ToList();

            foreach (var route in routes)
            {
                if (route.Id == id)
                {
                    route.Start = start;
                    route.Destination = destination;
                }
            }

            return this.PartialView("_RouteTable", routes);
        }

        [HttpGet]
        public ActionResult Routes(int id)
        {
            var routes = this.cs.GetListOfRoutes(id).Where(r => r.Id == id);
            return this.ToJson(routes);
        }

        [HttpPost]
        public ActionResult DeleteRoute(int id)
        {
            // do the route deletion here 


            // return a fresh view with available routes. 
            return this.GetRoutesForCompany(id);
        }


        [HttpGet]
        public ActionResult GetRoutesForCompany(int id)
        {
            var routes = this.cs.GetListOfRoutes(id);

            return this.PartialView("_RouteTable", routes);
        }

        [HttpGet]
        public ActionResult GetBussesForCompany(int id)
        {
            var busses = this.cs.GetBusses(id);

            return this.PartialView("_BussesTab", busses);
        }


    }
}

Ticket.UI.Web/Views/Company/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Company</h2>

Ticket.UI.Web/Views/Company/Register.cshtml
@model Ticket.Domain.Company

@{
    ViewBag.Title = "Register";
}
<div class="container">

    <div class="row">
        <div class="col-md-offset-1 col-md-10">
            <h2>Register your company</h2>

        </div>
    </div>
    <div class="col-md-8">
        @using (Html.BeginForm("Register", "Company", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.Label("Company name", new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("Contact person", new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.ContactPerson, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ContactPerson, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Fax, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Fax, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Fax, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Tin, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Tin, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Tin, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-4 col-md-8">
                        <input type="submit" value="Register" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Ticket.UI.Web/Views/Company/Setup.cshtml
@using Ticket.UI.Web.helpers
@model Ticket.UI.Web.ViewModels.CompanySetupViewModel

@{
    ViewBag.Title = "Setup";

    var setupData = Model.ToJson(); 
}

<div class="container" ng-controller="SetupModalController">
    <div class="row tab-v3">
        <div class="col-sm-3">
            <ul class="nav nav-pills nav-stacked">
                <li class="active">
                    <a href="#company" data-toggle="tab" aria-expanded="true">
                        <i class="fa fa-home"></i> Company
                    </a>
                </li>
                <li class="">
                    <a href="#busses" data-toggle="tab" aria-expanded="false">
                        <i class="fa fa-bus"></i> Busses
                    </a>
                </li>
                <li class="">
                    <a href="#routes" data-toggle="tab" aria-expanded="false">
                        <span class="item">
                            <span aria-hidden="true" class=" icon-graph"></span>
                            &nbsp; Routes
                        </span>
                    </a>
                </li>
                <li class="">
                    <a href="#payment" data-toggle="tab" aria-expanded="false">
                        <i class="fa  fa-cc-visa"></i> Account Info
                    </a>
                </li>
            </ul>
        </div>

        @*tab content starts here*@
        <div class="col-sm-9">
            <div class="tab-content">
                @Html.Partial("_CompanyTab", Model.Company)
                <div class="tab-pane fade" id="busses">

                    @Html.Partial("_BussesTab", Model.Busses)


                </div>
                <div class="tab-pane fade" id="routes">
                    @Html.Partial("_RoutesTab", Model.Routes)
                </div>
                <div class="tab-pane fade" id="payment">
                    @Html.Partial("_PaymentTab", Model.Company)
                </div>
            </div>
        </div>
        @*tab content ends here*@
    </div>
    <!-- Modal dialog -->
    <script type="text/ng-template" id="setupModal.html">
        <div class="modal-header">
            <button type="button" ng-click="close()" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title text-danger" id="setupModalHeaderText">{{params.modalHeader}}</h4>
        </div>

        <div class="modal-body">
            <h4 class="text-danger">{{params.modalBody}} </h4>
        </div>

        <div class="modal-footer">
            <button type="button" class="btn btn-danger" ng-click="proceed()">{{params.proceedText}}</button>
            <button type="button" class="btn btn-default" ng-click="close()">{{params.cancelText}}</button>
        </div>
    </script>
    <!-- Routes Add / Edit--->
    <script type="text/ng-template" id="RoutesModal.html">
        <div class="modal-header">
            <button type="button" ng-click="close()" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title text-success" id="setupModalHeaderText">Route</h4>
        </div>

        <div class="modal-body">
            <div class="form-horizontal">
                <div class="form-group">
                    <label class="control-label col-md-3"> Start</label>
                    <div class="col-md-8">
                        <input type="text" value="" ng-model="routeData.start.name" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3"> Destination</label>
                    <div class="col-md-8">
                        <input type="text" value="" ng-model="routeData.destination.name" class="form-control" />
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-success" ng-click="proceed()">Save</button>
            <button type="button" class="btn btn-default" ng-click="close()">Cancel</button>
        </div>
    </script>
    
    <!-- Bus Add / Edit--->
    <script type="text/ng-template" id="BusModal.html">
        <div class="modal-header">
            <button type="button" ng-click="close()" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title text-success" id="setupModalHeaderText">Bus</h4>
        </div>

        <div class="modal-body">
            <div class="form-horizontal">
                <div class="form-group">
                    <label class="control-label col-md-3"> Registration Number</label>
                    <div class="col-md-8">
                        <input type="text" value="" ng-model="bus.number" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3"> Capacity</label>
                    <div class="col-md-8">
                        <input type="text" value="" ng-model="bus.capacity" class="form-control" />
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-success" ng-click="proceed()">Save</button>
            <button type="button" class="btn btn-default" ng-click="close()">Cancel</button>
        </div>
    </script>
</div>
<script>
    angular.module("ticketify").value("setupData", @Html.Raw(setupData));
    angular.module("ticketify").value("urlBase", @Html.Raw("\""+  String.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~")) +"\""));
</script>

Ticket.UI.Web/Views/Company/_BusTable.cshtml
@model IList<Ticket.Domain.Bus>
<div>
    <table id="bustable" class="table table-condensed table-hover table-striped">
        <thead>
            <tr>
                <th>Registration</th>
                <th>Capacity</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="bus in busses">
                <td>{{bus.number}}</td>
                <td>{{bus.capacity}}</td>
                <td>
                    <a href="#" ng-click="edit(bus)"><i class="fa fa-edit"></i></a>
                </td>
                <td>
                    <a href="#" ng-click="remove(bus)"><i class="fa fa-remove"></i></a>
                </td>
            </tr>
        </tbody>
    </table>
</div>

Ticket.UI.Web/Views/Company/_BussesTab.cshtml
@model IList<Ticket.Domain.Bus>
<div class="panel panel-green margin-bottom-40">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-home"></i> Busses</h3>
    </div>
    <div class="panel-body">
        <button class="btn btn-success" ng-click="addBus()"><i class="fa fa-plus"></i> Add Bus</button>
        @Html.Partial("_BusTable", Model) 
    </div>
</div>

Ticket.UI.Web/Views/Company/_CompanyTab.cshtml
@model Ticket.Domain.Company

<div class="tab-pane fade active in" id="company">
    <div class="row">
        <div class="panel panel-green margin-bottom-40">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-home"></i> Company Information</h3>
            </div>
            <div class="panel-body">
                @{
                    var companyFormOptions = new AjaxOptions()
                    {
                        HttpMethod = "POST",
                        Url = Url.Action("UpdateCompanyInfo", "Company"),
                        OnSuccess = "ticketify.autoHide",
                        
                    };
                }
                @using (Ajax.BeginForm(companyFormOptions))
                {
                    @Html.AntiForgeryToken()

                 <div class="form-horizontal">
                        <hr />
                    
                        <div class="form-group">
                            @Html.Label("Company name", new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.HiddenFor(m => m.Id)

                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", ng_model="company.name"} })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>
                       
                        <div class="form-group">
                            @Html.Label("Contact person", new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.ContactPerson, new { htmlAttributes = new { @class = "form-control" , ng_model="company.contactPerson" } })
                                @Html.ValidationMessageFor(model => model.ContactPerson, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.Address, new { htmlAttributes = new
                                                                                                   {
                                                                                                       @class = "form-control",
                                                                                                       ng_model="company.address"
                                                                                                   } })
                                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new
                                                                                                 {
                                                                                                     @class = "form-control",
                                                                                                     ng_model="company.phone"
                                                                                                 
                                                                                                 } })
                                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Fax, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.Fax, new { htmlAttributes = new
                                                                                               {
                                                                                                   @class = "form-control",
                                                                                                   ng_model="company.fax"
                                                                                               
                                                                                               } })
                                @Html.ValidationMessageFor(model => model.Fax, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Tin, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.Tin, new { htmlAttributes = new
                                                                                               {
                                                                                                   @class = "form-control",
                                                                                                   ng_model="company.tin"
                                                                                               } })
                                @Html.ValidationMessageFor(model => model.Tin, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-4 col-md-8">
                                <input type="submit" value="Update" ng-click="validate" class="btn btn-success" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Ticket.UI.Web/Views/Company/_PaymentTab.cshtml
@model Ticket.Domain.Company

<div class="panel panel-green margin-bottom-40">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-home"></i> Account Information </h3>
    </div>
    <div class="panel-body">
        @{
            var paymentOptions = new AjaxOptions()
            {
                HttpMethod = "POST",
                Url = Url.Action("Payment", "Company"),
                InsertionMode = InsertionMode.InsertAfter,
                UpdateTargetId = "request-result",
                OnSuccess = "ticketify.autoHide"
            };
        }
        @using (Ajax.BeginForm("Register", "Company", paymentOptions))
        {
            @Html.AntiForgeryToken()

            <div id="request-result" class="auto-hide">

            </div>

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.Label("Mobile banking number", new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.HiddenFor(m => m.Id)
                        @Html.EditorFor(model => model.MobileBankingNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MobileBankingNumber, "", new { @class = "text-danger" })
                    </div>
                </div>
             

                <div class="form-group">
                    <div class="col-md-offset-4 col-md-8">
                        <input type="submit" value="Update" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Ticket.UI.Web/Views/Company/_RequestResult.cshtml
@using Ticket.UI.Web.Models
@model Ticket.UI.Web.Models.RequestResult


@switch (Model.ResultType)
{
    case RequestResultType.Success:
        {
            <div class="alert alert-success fade in alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <strong>Success!</strong>
                <p>@Model.Message</p>
            </div>
        }
        break;

    case RequestResultType.Warning:
        {
            <div class="alert alert-warning fade in alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <strong>Warning!</strong>
                <p>@Model.Message</p>
            </div>
        }
        break;

    case RequestResultType.Info:
        {
            <div class="alert alert-info fade in alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <strong>Info!</strong>
                <p>@Model.Message</p>
            </div>
        }
        break;

    case RequestResultType.Failed:
        {
            <div class="alert alert-danger fade in alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <strong>Error!</strong> 
                <p>@Model.Message</p>
            </div>
        }
        break;

}

Ticket.UI.Web/Views/Company/_RouteTable.cshtml
@model IList<Ticket.Domain.Route>
<div>
   <table id="routes-table" data-base="@Request.ApplicationPath" class="table table-condensed table-hover table-striped">
        <thead>
            <tr>
                <th>Start</th>
                <th>Destination</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="r in routes">
                <td> {{r.start.name}}  </td>
                <td> {{r.destination.name}} </td>
                <td><a href="#" ng-click="editRoute(r)"> <i class="fa fa-edit"></i> </a> </td>
                <td><a href="#" ng-click="removeRoute(r)"> <i class="fa fa-remove"></i> </a> </td>
            </tr>
        </tbody>
    </table>
</div>

Ticket.UI.Web/Views/Company/_RoutesTab.cshtml
@using System.ServiceModel.Channels
@using Microsoft.Ajax.Utilities
@model IEnumerable<Ticket.Domain.Route>

           

<div class="panel panel-green margin-bottom-40">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-home"></i> Routes </h3>
    </div>
    <div class="panel-body">
        <button class="btn btn-success" ng-click="addRoute()"><i class="fa fa-plus"></i> Add Route</button>
        @Html.Partial("_RouteTable", Model.ToList())
    </div>
</div>
          